steps:
- task: DotNetCoreCLI@2
  displayName: Restore, Build and Publish Files
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/MyHost
    workingDirectory: 
    arguments: --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: deploy
    artifactType: container

